# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Wikipedia
version:      0.6
version_from: lib/WWW/Wikipedia.pm
installdirs:  site
requires:
    HTML::Parser:                  1
    LWP::UserAgent:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
