---
abstract: 'Automated interface to the Wikipedia '
author:
  - 'Ed Summers <ehs@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Wikipedia
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  Text::Autoformat: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.95
