# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Wikipedia
version:      1.8
version_from: lib/WWW/Wikipedia.pm
installdirs:  site
requires:
    CGI:                           0
    LWP::UserAgent:                0
    Text::Autoformat:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
