--- 
abstract: "Automated interface to the Wikipedia "
author: 
  - Ed Summers <ehs@pobox.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-Wikipedia
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 0
  LWP::UserAgent: 0
  Text::Autoformat: 0
version: 1.93
